### ISSUE TITLE
Issue calculating the number of packets

### ISSUE THREAD

**Issue by tarunmangla** [chicago-cdac/netml#8]
The line below calculates the number of packets in a flow. However, the pkts data structure is a 2-tuple w/ the first field being the flow id and the second field being the list of packets. So, it should be len(pkts[1]) instead of len(pkts) which is always 2. 

https://github.com/chicago-cdac/netml/blob/d204074b6624cde5294d8de634c6df643c6523ef/src/netml/pparser/parser.py#L774

**Comment by feamster** [comment]
I also encountered this and pushed the bug fix. PR #11 @jesteria
