### ISSUE TITLE
Issue with feature dimensions

### ISSUE THREAD

**Issue by tarunmangla** [chicago-cdac/netml#9]
There seem to be two variables for the feature dimension: self.dim and dim. For calculating IAT features, only one of the variables is being updated. This leads to issues when appending header features. 

https://github.com/chicago-cdac/netml/blob/d204074b6624cde5294d8de634c6df643c6523ef/src/netml/pparser/parser.py#L808

Should there be only one variable for consistency?

**Comment by feamster** [comment]
I also discovered this. It is the same issue as #8, fixed in the open PR.
